/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;
import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo
 */
public class Principal extends javax.swing.JFrame {

    
    /**
     * Creates new form Principal
     */
    Password p;
    public Principal() {
        initComponents();
        txtClave.setEditable(true);
        cmdMostrar.setEnabled(false);
        cmdGuardar.setEnabled(true);
        cmdCambiar.setEnabled(false);
        cmdLimpiar.setEnabled(false);
        cmdEstabilidad.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        cmdMostrar = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdEstabilidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 100, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 30));
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 80, 30));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, 30));

        cmdCambiar.setText("Cambiar Contraseña");
        cmdCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Datos Actuales:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        txtResultado.setEditable(false);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, 30));

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 30));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, 30));

        cmdEstabilidad.setText("Estabilidad");
        cmdEstabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEstabilidadActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEstabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(517, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       
    int longitud;
    String clave;
    clave = txtClave.getText();
    longitud = clave.length();
    p = new Password(longitud,clave); 
    clave = p.getClave();
    longitud = p.getLongitud();
    txtResultado.setText("Su contraseña actual es: "+clave+" y su longitud es: "+longitud);
   
       
        txtClave.setEditable(false);
        cmdMostrar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdCambiar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
        cmdEstabilidad.setEnabled(true);
       
     
       
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
    
    int longitud;
    String clave;
    if(txtClave.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Espacio vacío, Favor llenarlo","ERROR",JOptionPane.ERROR_MESSAGE);
        txtClave.requestFocusInWindow();
    }else {
        clave = txtClave.getText();
        longitud = clave.length();
        p = new Password (longitud,clave);
        JOptionPane.showMessageDialog(this, "¡Contraseña Guardada Correctamente!");
        cmdCambiar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        txtClave.setEditable(false);
        cmdEstabilidad.setEnabled(true);
    }
    
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarActionPerformed
        
        String cambio;
        int longitud,sw = 1;
        
        do {
            try {
                cambio = JOptionPane.showInputDialog(this, "Ingrese su contraseña nueva");
                longitud = cambio.length();
                p = new Password(longitud, cambio);
                txtClave.setText(cambio);
                txtResultado.setText("");
                JOptionPane.showMessageDialog(this, "¡Contraseña Modificada!");
                sw = 1;
            } catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);
        
        txtClave.setEditable(false);
        cmdMostrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdCambiar.setEnabled(false);
        cmdLimpiar.setEnabled(false);
        cmdEstabilidad.setEnabled(true);

    }//GEN-LAST:event_cmdCambiarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
       txtClave.setText("");
       txtResultado.setText("");
       txtClave.requestFocusInWindow();
       
       txtClave.setEditable(true);
        cmdMostrar.setEnabled(false);
        cmdGuardar.setEnabled(true);
        cmdCambiar.setEnabled(false);
        cmdLimpiar.setEnabled(false);
       cmdEstabilidad.setEnabled(false);
       
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdEstabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEstabilidadActionPerformed
        String clave;
        String aux;
        int longitud;       
        clave = txtClave.getText();
        longitud = clave.length();
        p = new Password(longitud, clave);
        aux = p.estabilidad();
        txtResultado.setText(""+aux);
        
        txtClave.setEditable(false);
        cmdMostrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdCambiar.setEnabled(true);
        cmdLimpiar.setEnabled(true);
       cmdEstabilidad.setEnabled(false);
    }//GEN-LAST:event_cmdEstabilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdEstabilidad;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
